baseURL = "https://www.tbk.fi/"
languageCode = "en-us"
title = "TBK"
theme = "stratosphere"

[minify]
    minifyOutput = true

[params]
    author = "Tuomo Björk"

    # meta-links
    url_github  = "https://github.com/tbkfi"
    url_signal  = "https://signal.me/#eu/bj5Mo-n3PuDyGs9S_dsGcb5L6zQyDFINdvHlEYFKam-UhveaGfRLZ7XDXfqE268I"
    url_steam   = "https://steamcommunity.com/id/tbkfi"
    url_discord = ""

    # meta-status
    url_directory = "https://dir.tbk.fi/"
    url_portal    = "https://portal.tbk.fi/"

    # description
    desc_post = "topic specific content pieces"
    desc_note = "various insights on projects and media"
    desc_log  = "media logs"

[markup]
    [markup.highlight]
        style = "friendly"
        tabWidth = 4
        
        noClasses = true
        guessSyntax = false
        wrapperClass = 'highlight'
        
        lineNos = true
        anchorLineNos = false
        codeFences = true
        lineNumbersInTable = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
